package com.wells.forage.entities;

import javax.persistence.*;
import java.util.Objects;

/**
 * Represents a Client in the system.
 * This entity will be mapped to a 'client' table in the database.
 */
@Entity
@Table(name = "client")
public class Client {

    /**
     * The unique identifier for the client.
     * It is the primary key and will be auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The first name of the client.
     */
    @Column(name = "first_name")
    private String firstName;

    /**
     * The last name of the client.
     */
    @Column(name = "last_name")
    private String lastName;

    /**
     * The financial advisor who manages this client.
     * This establishes a many-to-one relationship. The '@JoinColumn' annotation
     * defines the foreign key column in this table that links to the FinancialAdvisor.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "advisor_id")
    private FinancialAdvisor advisor;

    /**
     * The portfolio owned by this client.
     * This establishes a one-to-one relationship. The 'mappedBy' attribute indicates
     * that the 'client' field in the Portfolio entity owns the relationship.
     */
    @OneToOne(mappedBy = "client", cascade = CascadeType.ALL, orphanRemoval = true)
    private Portfolio portfolio;

    // --- Constructors ---

    public Client() {
    }

    public Client(String firstName, String lastName, FinancialAdvisor advisor) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.advisor = advisor;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public FinancialAdvisor getAdvisor() {
        return advisor;
    }

    public void setAdvisor(FinancialAdvisor advisor) {
        this.advisor = advisor;
    }

    public Portfolio getPortfolio() {
        return portfolio;
    }

    public void setPortfolio(Portfolio portfolio) {
        this.portfolio = portfolio;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Client client = (Client) o;
        return Objects.equals(id, client.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
