package com.wells.forage.entities;

import javax.persistence.*;
import java.util.List;
import java.util.Objects;

/**
 * Represents a Financial Advisor in the system.
 * This entity will be mapped to a 'financial_advisor' table in the database.
 */
@Entity
@Table(name = "financial_advisor")
public class FinancialAdvisor {

    /**
     * The unique identifier for the financial advisor.
     * It is the primary key and will be auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The first name of the financial advisor.
     */
    @Column(name = "first_name")
    private String firstName;

    /**
     * The last name of the financial advisor.
     */
    @Column(name = "last_name")
    private String lastName;

    /**
     * The list of clients managed by this financial advisor.
     * This establishes a one-to-many relationship. The 'mappedBy' attribute indicates
     * that the 'advisor' field in the Client entity owns the relationship.
     */
    @OneToMany(mappedBy = "advisor", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Client> clients;

    // --- Constructors ---

    public FinancialAdvisor() {
    }

    public FinancialAdvisor(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public List<Client> getClients() {
        return clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FinancialAdvisor that = (FinancialAdvisor) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
