package com.wells.forage.entities;

import javax.persistence.*;
import java.util.List;
import java.util.Objects;

/**
 * Represents a Portfolio in the system.
 * This entity will be mapped to a 'portfolio' table in the database.
 */
@Entity
@Table(name = "portfolio")
public class Portfolio {

    /**
     * The unique identifier for the portfolio.
     * It is the primary key and will be auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The client who owns this portfolio.
     * This establishes a one-to-one relationship. The '@JoinColumn' annotation
     * defines the foreign key column in this table that links to the Client.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    private Client client;

    /**
     * The list of securities within this portfolio.
     * This establishes a one-to-many relationship. The 'mappedBy' attribute indicates
     * that the 'portfolio' field in the Security entity owns the relationship.
     */
    @OneToMany(mappedBy = "portfolio", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Security> securities;

    // --- Constructors ---

    public Portfolio() {
    }

    public Portfolio(Client client) {
        this.client = client;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public List<Security> getSecurities() {
        return securities;
    }

    public void setSecurities(List<Security> securities) {
        this.securities = securities;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Portfolio portfolio = (Portfolio) o;
        return Objects.equals(id, portfolio.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
