package com.wells.forage.entities;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Represents a Security in the system.
 * This entity will be mapped to a 'security' table in the database.
 */
@Entity
@Table(name = "security")
public class Security {

    /**
     * The unique identifier for the security.
     * It is the primary key and will be auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the security.
     */
    @Column(name = "name")
    private String name;

    /**
     * The category of the security.
     */
    @Column(name = "category")
    private String category;

    /**
     * The purchase date of the security.
     */
    @Column(name = "purchase_date")
    private Date purchaseDate;

    /**
     * The purchase price of the security.
     */
    @Column(name = "purchase_price")
    private BigDecimal purchasePrice;

    /**
     * The quantity of the security held.
     */
    @Column(name = "quantity")
    private Integer quantity;

    /**
     * The portfolio that contains this security.
     * This establishes a many-to-one relationship. The '@JoinColumn' annotation
     * defines the foreign key column in this table that links to the Portfolio.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "portfolio_id")
    private Portfolio portfolio;

    // --- Constructors ---

    public Security() {
    }

    public Security(String name, String category, Date purchaseDate, BigDecimal purchasePrice, Integer quantity, Portfolio portfolio) {
        this.name = name;
        this.category = category;
        this.purchaseDate = purchaseDate;
        this.purchasePrice = purchasePrice;
        this.quantity = quantity;
        this.portfolio = portfolio;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Date getPurchaseDate() {
        return purchaseDate;
    }

    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Portfolio getPortfolio() {
        return portfolio;
    }

    public void setPortfolio(Portfolio portfolio) {
        this.portfolio = portfolio;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Security security = (Security) o;
        return Objects.equals(id, security.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
